#!/bin/bash
PATH="node_modules/.bin:$PATH"

echo -e "---------------------\nPreparing for release\n---------------------"
echo "👾  Installing node modules."
npm install
echo "📑  Compiling distribution files for release."
npm run -s dist && git add dist/* && exit 0
exit 1
